---
layout: post
title: "Python程序员的10个常见错误的学习总结"
description: "Python程序员的10个常见错误的学习总结"
category: "python"
tags: [python技巧]
---

<h3>常见错误1：在函数参数中乱用表达式作为默认值</h3>

<p>参考这里<a href="http://codetheme.sinaapp.com/codetheme/7/"><strong>http://codetheme.sinaapp.com/codetheme/7/</strong></a></p>

<h3>常见错误2：不正确的使用类变量</h3>

<p>实例如下：</p>

<pre><code>#!/usr/bin/env python
# coding=utf-8
class A(object):
    x = 1

class B(A):  # B继承A
    pass

class C(A):  # C继承A
    pass

print A.x, B.x, C.x
B.x = 2
print A.x, B.x, C.x
A.x = 3
print A.x, B.x, C.x
</code></pre>

<p>这个输出结果，想必一目了然：</p>

<pre><code>1 1 1
1 2 1
3 2 3
</code></pre>

<blockquote>
  <p>在Python里，类变量通常在内部被当做<strong>字典</strong>来处理并遵循通常所说的<strong>方法解析顺序</strong>（Method Resolution Order (MRO)）。因此在上面的代码中，因为属性x在类C中找不到，因此它会往上去它的基类中查找（在上面的例子中只有A这个类，当然Python是支持多重继承（multiple inheritance）的）。换句话说，C没有它自己独立于A的属性x。因此对C.x的引用实际上是对A.x的引用。（B.x不是对A.x的引用是因为在第二步里B.x=2将B.x引用到了2这个对象上，倘若没有如此，B.x仍然是引用到A.x上的</p>
</blockquote>

<!--more-->

<p><strong>在使用类变量时，一定要注意Python继承的特性：</strong>，</p>

<h3>(1).在继承中基类的构造方法<strong>init</strong>()不会被自动调用</h3>

<h3>(2).在调用基类的方法时，需要加上基类的类名前缀，且需要带上self参数变量</h3>

<h3>(3).Python总是首先查找对应类型的方法和属性，如果它不能在派生类中找到对应的，它才开始到基类中逐个查找。</h3>

<p>如下扩展就很好理解了：</p>

<pre><code>#!/usr/bin/env python
# coding=utf-8
class A(object):
    x = 1

class B(A):  # B继承A
    x = 100

class C(B):  # C继承B
    x = 200

class D(C): # D继承C
    pass

print A.x, B.x, C.x, D.x
B.x = 2
print A.x, B.x, C.x, D.x
A.x = 3
print A.x, B.x, C.x, D.x
</code></pre>

<h3>常见错误3：在异常处理时错误的使用参数</h3>

<pre><code>#!/usr/bin/env python
# coding=utf-8
try:
    l = ['a', 'b']
    int(l[2])   # 这里涉及两个异常，ValueError,IndexError

except ValueError, IndexError: #想要捕获两个异常
    pass
</code></pre>

<p>这样报错如下；</p>

<pre><code>Traceback (most recent call last):
  File "&lt;stdin&gt;", line 3, in &lt;module&gt;
 IndexError: list index out of range
</code></pre>

<p>原因在于<strong>在Python 2.x里面，语法except Exception, e是用来将异常和这个可选的参数绑定起来（即这里的e）</strong>，以用来在后面查看的。因此，在上面的代码中，IndexError异常不会被except语句捕捉到；而最终<strong>ValueError这个异常被绑定在了一个叫做IndexError的参数上。</strong></p>

<blockquote>
  <p><strong>在except语句中捕捉多个异常的正确做法是将所有想要捕捉的异常放在一个元组（tuple）里并作为第一个参数给except语句</strong>。并且，为移植性考虑，使用<strong>as</strong>关键字，因为Python 2和Python 3都支持这样的语法，例如：</p>
</blockquote>

<pre><code>except (ValueError, IndexError) as e: #想要捕获两个异常
</code></pre>

<h3>常见错误4：误解Python作用域的规则</h3>

<p>这段代码如下：</p>

<pre><code>#!/usr/bin/env python
# coding=utf-8
x = 1
def foo():
    x += 1
    return x

print foo()
</code></pre>

<p>在运行中会报这样的错误：</p>

<pre><code>Traceback (most recent call last):
  File "2.py", line 8, in &lt;module&gt;
    print foo()
  File "2.py", line 5, in foo
    x += 1
UnboundLocalError: local variable 'x' referenced before assignment
</code></pre>

<p>这是因为Python的作用域解析是基于叫做<strong>LEGB</strong>（Local（本地），Enclosing（封闭），Global（全局），Built-in（内置））的规则进行操作的。在一个作用域里面给一个<strong>变量赋值</strong>的时候，Python自动认为这个变量是这个作用域的<strong>本地变量</strong>，并<strong>屏蔽</strong>作用域外的同名的变量。</p>

<p>解决办法可以传参，如：<code>foo(x)</code>, 对于上述情况在列表中也会常常出现，如下：</p>

<pre><code>#!/usr/bin/env python
# coding=utf-8
lis = [1, 2, 3]
def foo():
    lis += 4

print foo()
print lis
</code></pre>

<p>这段代码出错信息同上，原因也同上就是在一个作用域里面给一个<strong>变量赋值</strong>，这里是(lis= lis+4)的时候，Python自动认为这个变量是这个作用域的<strong>本地变量</strong>，并<strong>屏蔽</strong>作用域外的同名的变量。</p>

<p>解决办法就是<strong>在作用域中激活作用域外的同名变量</strong>，如：将<code>lis += 4</code>， 改成 <code>lis.append(4)</code> 就OK啦。</p>

<h3>常见错误5：在遍历列表的同时又在修改这个列表</h3>

<pre><code>&gt;&gt;&gt; odd = lambda x : bool(x % 2)
&gt;&gt;&gt; numbers = [n for n in range(10)]
&gt;&gt;&gt; for i in range(len(numbers)):
...     if odd(numbers[i]):
...         del numbers[i]   # 在遍历列表时删掉列表的元素。
...         
...     
... 
Traceback (most recent call last):
  File "&lt;input&gt;", line 2, in &lt;module&gt;
IndexError: list index out of range
&gt;&gt;&gt; 
</code></pre>

<p>注意：在遍历列表不能增删其元素，解决办法<code>numbers[:] = [n for n in numbers if not odd(n)]</code></p>

<p><strong>放松下吧：</strong></p>

<blockquote>
  <p>你应该看过好莱坞大片《骇客帝国》，相信你会对电影中那些神奇的场景着迷。在Neo的眼里任何东西都能以计算机字节流的形式展现，你是否也想做一个很有黑客范儿的数据流的桌面呢？</p>
</blockquote>

<pre><code>sudo apt-get install cmatrix
cmatrix
</code></pre>

<p><img src="http://www.webhek.com/vaikan-images/uploads/2013/7675/cmatrix.gif" alt="" /></p>

<h2>参考</h2>

<p><a href="http://blog.jobbole.com/68256/"><strong>1.Python程序员的10个常见错误</strong></a></p>

<p><a href="http://www.cnblogs.com/Joans/archive/2012/11/09/2757368.html"><strong>2.python语法学习面向对象之继承</strong></a></p>
